# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creation_Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(verbose_name='Creation time')),
                ('last_modified', models.DateTimeField(verbose_name='Last modified')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_size', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('annotated_name', models.CharField(max_length=200)),
                ('storage_path', models.CharField(max_length=200)),
                ('GUID', models.IntegerField(default=0)),
                ('filetype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=200)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
